### ISSUE TITLE
Custom mappings to BeanMapper

### ISSUE THREAD

**Issue by apunkto** [nortal/petit#7]
EMPIS: BeanMapper.java

A la

    BeanRowMapper<AdsAadress> mapper = BeanRowMapper.get(AdsAadress.class);
    mapper.add("aadressTyyp", "aadress_tyyp_kood");

**Comment by basileus-v** [comment]
Doesn't @Column solve this problem?
```java
@Column(name="aadress_tyyp_kood")
String addressTyyp;
```

**Comment by apunkto** [comment]
aadress_tyyp_kood here would be a Transient field, and is only needed in one specific query. 

for example: select a.*, b.foo from a, b -> into model object A with a transient field b.

**Comment by basileus-v** [comment]
```java
class B extends A {
  String b;
}
```

**Comment by apunkto** [comment]
That would be one solution, but it would not be too nice to have a separate classes like
ObjectWithField1, ObjectWithField2, ObjectWithFields1And2 etc..

**Comment by AlrikP** [comment]
Added method add(String property, String columnName) to the BeanMapper. This allows to map additional fields - for example bean properties that are annotated with @Transient annotation and usually excluded from mappings.
Release in 1.0.4 version.

**Comment by jimmytheneutrino** [comment]
I am late for the party, but I opt that there is a principally better solution.

The BeanMapper is, as intended, a lightweight wrapper over BeanMapping. So it will yield much simpler code to have BeanMapper immutable.

So, instead of mapper.add it is better to use mapper.with or mapper.plus. 

If you are ok with that, I'll submit a patch in the evening.

**Comment by AlrikP** [comment]
If I understand correctly you just want to change the name of method "add" to "with" ? 
Or did you have something else in mind ?

**Comment by jimmytheneutrino** [comment]
Well, instead of
```
BeanRowMapper<AdsAadress> mapper = BeanRowMapper.get(AdsAadress.class);
mapper.add("aadressTyyp", "aadress_tyyp_kood");
```
it would look like this
```
BeanRowMapper<AdsAadress> mapper = 
BeanRowMapper.get(AdsAadress.class).plus("aadressTyyp", "aadress_tyyp_kood");
```
But more importantly, it would make things simpler by not requiring two beanmappings inside a beanmapper (instead, we just get a new beanmapper with a new beanmapping).
